#!/bin/bash

dots_location="~/.dotfiles"

function symlink {
  [[ "$2" ]] && link_source="$2"
  [[ -z "$2" ]] && link_source="$1"
  location=$(cat example-config | sed '/^#/d' | awk '{print $1}' | grep -i $1)
  echo $link_source
  echo $location
  ln -s $link_source $location
}

push_all() {
	echo "push_all function"
}

push_single() {
	package_name="$1"
	echo "Pushing $package_name..."
	symlink $package_name
	echo "Done"
}

push_file() {
	file_name="$1"
	echo "push_file function"
	echo "Will push $file_name"
}

usage() {
	echo "usage function"
	echo "Outputs help for program"
}

version() {
	echo "version function"
	echo "Outputs version"
}

while [ "$1" != "" ]; do
	case $1 in
		--dots-location )
			shift
			dots_location="$1"
			;;
		-a | --all )
			push_all
			exit
			;;
		-s | --single )
			shift
			package_name="$1"
			push_single $package_name
			exit
			;;
		-f | --file )
			shift
			file_name="$1"
			push_file $file_name
			exit
			;;
		-h | --help )
			usage
			exit
			;;
		-v | --version )
			version
			exit
			;;
		* )
			usage
			exit 1
			;;
	esac
	shift
done
