#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}"   )" >/dev/null 2>&1 && pwd)" # Location of the script
dots_location="$SCRIPT_DIR"
config_file="$SCRIPT_DIR/example-config"

function symlink {
  if [ "$2" ]
	then
		link_files="$HOME/$2/*" && package_name=$1
	else
		link_files="$dots_location/$(cat $config_file  | sed '/^#/d' | grep -i bash/ | awk '{print $1}')"
	fi
  location=$(cat $config_file | sed 's|~|'$HOME'|g' | sed '/^#/d' | grep -i $1 | awk '{print $2}')
  echo "Source: $link_files"
  echo "Location: $location"
  echo "ln -s $link_files $location" # Changed this to echo the link command whilst this is in development
}

push_all() {
	echo "push_all function"
}

push_single() {
	package_name="$1"
	echo "Pushing $package_name..."
	symlink $package_name
	echo "Done"
}

push_file() {
	file_name="$1"
	echo "push_file function"
	echo "Will push $file_name"
}

usage() {
	echo "usage function"
	echo "Outputs help for program"
}

version() {
	echo "version function"
	echo "Outputs version"
}

while [ "$1" != "" ]; do
	case $1 in
		--dots-location )
			shift
			dots_location="$1"
			;;
		-a | --all )
			push_all
			exit
			;;
		-s | --single )
			shift
			package_name="$1"
			push_single $package_name
			exit
			;;
		-f | --file )
			shift
			file_name="$1"
			push_file $file_name
			exit
			;;
		-h | --help )
			usage
			exit
			;;
		-v | --version )
			version
			exit
			;;
		* )
			usage
			exit 1
			;;
	esac
	shift
done
